### ISSUE TITLE
[Bug]: Cannot build fonts

### ISSUE THREAD

**Issue by rusmux** [web-infra-dev/rslib#558]
### Version

```sh
System:
    OS: macOS 15.2
    CPU: (8) arm64 Apple M1
    Memory: 72.06 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 131.0.6778.140
    Safari: 18.2
  npmPackages:
    @rslib/core: ^0.1.3 => 0.1.3
```

### Details

I want to create a lib with shared fonts. In `src/fonts.css` I have:

```css
@font-face {
    font-family: 'Inter';
    font-style: normal;
    font-weight: 400;
    src: url("./fonts/Inter-Regular.woff2") format("woff2");
}
```

In `rslib.config.mjs`:

```js
export default defineConfig({
    source: {
        entry: {
            index: ['./src/**'],
        },
    },
    lib: [{format: 'esm', bundle: false}],
    output: {target: 'web'},
    plugins: [pluginReact()],
});
```

When I run `pnpm build`, I get error:

```sh
error   Compile error: 
Failed to compile, check the errors for troubleshooting.
File: .../src/fonts.css?__rslib_entry__:1:1
  × Module build failed:
  ╰─▶   × TypeError: Cannot read properties of undefined (reading '__esModule')
```

### Reproduce link

https://github.com/rusmux/rslib-issue-demo

### Reproduce Steps

```shell
git clone git@github.com:rusmux/rslib-issue-demo.git
cd rslib-issue-demo
pnpm install
pnpm build
```
